name: "Podcast Generator"
author: "Suyash Madhavi"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The committer's email address
    required: true
    default: noreply@github.com
  name:
    description: The committer's name
    required: true
    default: GitHub Actions Bot
